/// <reference types="node" />
import fs from 'fs'
import path from 'path'
import YAML from 'yaml'
import { CompiledRole } from '../types'
import { WORKSPACE_DIR } from '../core/recon'

export const DOCKER_AGENT_FILE = 'docker-agent.yaml'

const ORCHESTRATOR_ID = 'orchestrator'

interface DockerToolset {
  type: string
  [key: string]: unknown
}

interface DockerAgentDef {
  model: string
  description: string
  instruction: string
  sub_agents?: string[]
  toolsets?: DockerToolset[]
}

interface DockerAgentConfig {
  agents: Record<string, DockerAgentDef>
}

export function mapToolsToDockerToolsets(allow: string[]): DockerToolset[] {
  const toolsets: DockerToolset[] = []
  const set = new Set(allow.map(t => t.toLowerCase()))

  const hasRead = ['read', 'grep', 'glob', 'list'].some(t => set.has(t))
  const hasWrite = ['edit', 'write'].some(t => set.has(t))
  if (hasRead || hasWrite) toolsets.push({ type: 'filesystem' })
  if (set.has('bash') || set.has('shell')) toolsets.push({ type: 'shell' })
  if (set.has('todowrite') || set.has('todo')) toolsets.push({ type: 'todo', shared: true })
  if (set.has('webfetch') || set.has('fetch')) toolsets.push({ type: 'fetch' })
  if (set.has('websearch')) {
    toolsets.push({ type: 'mcp', ref: 'docker:duckduckgo' })
  }

  // Coordinator needs explicit reasoning + parallel dispatch. The `think`
  // toolset is harmless for models with native reasoning.
  if (!toolsets.some(t => t.type === 'think')) toolsets.push({ type: 'think' })

  return toolsets
}

export function subAgentsFor(roleId: string, allIds: string[]): string[] {
  if (roleId === ORCHESTRATOR_ID) return allIds.filter(id => id !== ORCHESTRATOR_ID)
  return []
}

export function toolsetsFor(roleId: string, allow: string[]): DockerToolset[] {
  const base = mapToolsToDockerToolsets(allow)
  if (roleId === ORCHESTRATOR_ID && !base.some(t => t.type === 'background_agents')) {
    // `transfer_task` is sequential; `background_agents` enables fan-out.
    // Insert after `think` when present so dispatch reads naturally.
    const thinkIdx = base.findIndex(t => t.type === 'think')
    const bg = { type: 'background_agents' }
    if (thinkIdx >= 0) base.splice(thinkIdx + 1, 0, bg)
    else base.push(bg)
  }
  return base
}

function dockerInstructionFor(roleId: string, prompt: string): string {
  if (roleId !== ORCHESTRATOR_ID) return prompt
  return [
    prompt.trim(),
    '',
    '## Docker Agent runtime notes',
    '',
    'You run inside Docker Agent, not opencode. Delegate with `transfer_task(agent, task, expected_output)` for sequential work and `run_background_agent(agent, task)` + `wait_background_agents(task_ids)` for independent work that can run in parallel. Do not use `@agent` mentions — use the `sub_agents` available to you.',
  ].join('\n')
}

export function buildDockerAgentConfig(roles: CompiledRole[]): DockerAgentConfig {
  const ids = roles.map(r => r.id)
  const agents: Record<string, DockerAgentDef> = {}
  for (const role of roles) {
    const subAgents = subAgentsFor(role.id, ids)
    agents[role.id] = {
      model: role.frontmatter.model,
      description: `${role.frontmatter.name} — legioni team agent`,
      instruction: dockerInstructionFor(role.id, role.prompt),
      ...(subAgents.length ? { sub_agents: subAgents } : {}),
      toolsets: toolsetsFor(role.id, role.frontmatter.tools.allow),
    }
  }
  return { agents }
}

export function dockerAgentFilePath(cwd: string): string {
  return path.join(cwd, WORKSPACE_DIR, DOCKER_AGENT_FILE)
}

export function writeAgents(roles: CompiledRole[], cwd = process.cwd()): string[] {
  const config = buildDockerAgentConfig(roles)
  const header = '# Generated by legioni. Do not edit manually — re-run `legioni install --host docker-agent` to refresh.\n'
  const body = YAML.stringify(config)
  const filePath = dockerAgentFilePath(cwd)
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, header + body, 'utf-8')
  return [filePath]
}

export function upsertProjectInstructions(cwd: string): {
  configPath: string
  added: boolean
  tracked: boolean
} {
  // The team file itself lives under `.legioni/` which is already git-excluded
  // by `legioni init`. Nothing to add to host config files.
  return { configPath: dockerAgentFilePath(cwd), added: false, tracked: false }
}
