import fs from 'fs'
import path from 'path'

export const WORKSPACE_DIR = '.hexis'

export function runRecon(cwd: string): void {
  const profile = buildProjectProfile(cwd)
  const wsDir = path.join(cwd, WORKSPACE_DIR)
  fs.mkdirSync(wsDir, { recursive: true })
  fs.writeFileSync(path.join(wsDir, 'project.md'), profile, 'utf-8')
}

function buildProjectProfile(cwd: string): string {
  const sections: string[] = ['# Project Profile\n\n_Generated by hexis recon. Do not edit manually — re-run `hexis update` to refresh._']

  const { language, framework, buildCmd, testCmd, lintCmd } = detectStack(cwd)

  const stackLines = [`- Language: ${language}`]
  if (framework) stackLines.push(`- Framework: ${framework}`)
  sections.push(`## Stack\n\n${stackLines.join('\n')}`)

  const cmdLines = [
    buildCmd && `- Build: \`${buildCmd}\``,
    testCmd && `- Test: \`${testCmd}\``,
    lintCmd && `- Lint/format: \`${lintCmd}\``,
  ].filter(Boolean) as string[]
  if (cmdLines.length) sections.push(`## Commands\n\n${cmdLines.join('\n')}`)

  const structure = getTopLevelStructure(cwd)
  sections.push(`## Directory Structure\n\n\`\`\`\n${structure}\n\`\`\``)

  const existing = readExistingInstructions(cwd)
  if (existing) sections.push(`## Existing Instructions\n\n${existing}`)

  return sections.join('\n\n')
}

function detectStack(cwd: string) {
  let language = 'unknown'
  let framework: string | null = null
  let buildCmd: string | null = null
  let testCmd: string | null = null
  let lintCmd: string | null = null

  const pkgPath = path.join(cwd, 'package.json')
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'))
      const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) }
      language =
        'typescript' in deps || fs.existsSync(path.join(cwd, 'tsconfig.json'))
          ? 'TypeScript'
          : 'JavaScript'
      if ('next' in deps) framework = 'Next.js'
      else if ('react' in deps) framework = 'React'
      else if ('vue' in deps) framework = 'Vue'
      else if ('svelte' in deps) framework = 'Svelte'
      else if ('express' in deps) framework = 'Express'
      else if ('fastify' in deps) framework = 'Fastify'
      else if ('hono' in deps) framework = 'Hono'
      const scripts = pkg.scripts ?? {}
      buildCmd = scripts.build ? 'npm run build' : null
      testCmd = scripts.test
        ? 'npm test'
        : scripts['test:run']
          ? 'npm run test:run'
          : null
      lintCmd = scripts.lint ? 'npm run lint' : scripts.format ? 'npm run format' : null
    } catch {
      // malformed package.json — skip
    }
  } else if (
    fs.existsSync(path.join(cwd, 'pyproject.toml')) ||
    fs.existsSync(path.join(cwd, 'setup.py'))
  ) {
    language = 'Python'
    const tomlPath = path.join(cwd, 'pyproject.toml')
    if (fs.existsSync(tomlPath)) {
      const content = fs.readFileSync(tomlPath, 'utf-8').toLowerCase()
      if (content.includes('django')) framework = 'Django'
      else if (content.includes('fastapi')) framework = 'FastAPI'
      else if (content.includes('flask')) framework = 'Flask'
      else if (content.includes('airflow')) framework = 'Apache Airflow'
    }
    testCmd = fs.existsSync(path.join(cwd, 'pytest.ini')) ? 'pytest' : 'pytest'
    lintCmd = 'ruff check .'
  } else if (fs.existsSync(path.join(cwd, 'go.mod'))) {
    language = 'Go'
    buildCmd = 'go build ./...'
    testCmd = 'go test ./...'
    lintCmd = 'golangci-lint run'
  } else if (fs.existsSync(path.join(cwd, 'Cargo.toml'))) {
    language = 'Rust'
    buildCmd = 'cargo build'
    testCmd = 'cargo test'
    lintCmd = 'cargo clippy'
  } else if (fs.existsSync(path.join(cwd, 'pom.xml'))) {
    language = 'Java'
    framework = 'Maven'
    buildCmd = 'mvn compile'
    testCmd = 'mvn test'
  } else if (
    fs.existsSync(path.join(cwd, 'build.gradle')) ||
    fs.existsSync(path.join(cwd, 'build.gradle.kts'))
  ) {
    language = 'Java/Kotlin'
    framework = 'Gradle'
    buildCmd = './gradlew build'
    testCmd = './gradlew test'
  }

  return { language, framework, buildCmd, testCmd, lintCmd }
}

const IGNORED = new Set(['node_modules', '__pycache__', 'target', 'dist', 'build', '.git', '.hexis'])

function getTopLevelStructure(cwd: string): string {
  const entries = fs
    .readdirSync(cwd)
    .filter(e => !e.startsWith('.') && !IGNORED.has(e))
    .sort()
    .map(e => {
      const isDir = fs.statSync(path.join(cwd, e)).isDirectory()
      return isDir ? `${e}/` : e
    })

  let result = entries.join('\n')

  for (const candidate of ['src', 'lib', 'app', 'pkg', 'packages']) {
    const dir = path.join(cwd, candidate)
    if (fs.existsSync(dir) && fs.statSync(dir).isDirectory()) {
      const sub = fs
        .readdirSync(dir)
        .filter(e => !e.startsWith('.') && !IGNORED.has(e))
        .sort()
        .slice(0, 20)
        .map(e => {
          const isDir = fs.statSync(path.join(dir, e)).isDirectory()
          return `  ${e}${isDir ? '/' : ''}`
        })
      if (sub.length) result += `\n\n${candidate}/:\n${sub.join('\n')}`
      break
    }
  }

  return result
}

function readExistingInstructions(cwd: string): string | null {
  for (const filename of ['AGENTS.md', 'CLAUDE.md', '.cursorrules']) {
    const filePath = path.join(cwd, filename)
    if (fs.existsSync(filePath)) {
      const content = fs.readFileSync(filePath, 'utf-8').trim()
      if (content) return `_Source: \`${filename}\`_\n\n${content}`
    }
  }
  return null
}
