import fs from 'fs'
import path from 'path'

export const WORKSPACE_DIR = '.legioni'

export function runRecon(cwd: string): void {
  const profile = buildProjectProfile(cwd)
  const wsDir = path.join(cwd, WORKSPACE_DIR)
  fs.mkdirSync(wsDir, { recursive: true })
  fs.writeFileSync(path.join(wsDir, 'project.md'), profile, 'utf-8')
}

function buildProjectProfile(cwd: string): string {
  const sections: string[] = ['# Project Profile\n\n_Generated by legioni recon. Do not edit manually — re-run `legioni update` to refresh._']

  const { language, framework, buildCmd, testCmd, targetedTestCmd, lintCmd } = detectStack(cwd)

  const stackLines = [`- Language: ${language}`]
  if (framework) stackLines.push(`- Framework: ${framework}`)
  sections.push(`## Stack\n\n${stackLines.join('\n')}`)

  const cmdLines = [
    buildCmd && `- Build: \`${buildCmd}\``,
    testCmd && `- Test: \`${testCmd}\``,
    targetedTestCmd && `- Targeted test: \`${targetedTestCmd}\``,
    lintCmd && `- Lint/format: \`${lintCmd}\``,
  ].filter(Boolean) as string[]
  if (cmdLines.length) sections.push(`## Commands\n\n${cmdLines.join('\n')}`)

  const structure = getTopLevelStructure(cwd)
  sections.push(`## Directory Structure\n\n\`\`\`\n${structure}\n\`\`\``)

  const existingFile = findExistingInstructionsFile(cwd)
  if (existingFile) {
    sections.push(`## Existing Instructions\n\n_\`${existingFile}\` is present in this repo and is loaded natively by the host — its contents are not duplicated here._`)
  }

  const securitySection = buildSecuritySection(cwd, language)
  if (securitySection) sections.push(securitySection)

  return sections.join('\n\n')
}

function detectStack(cwd: string) {
  let language = 'unknown'
  let framework: string | null = null
  let buildCmd: string | null = null
  let testCmd: string | null = null
  let targetedTestCmd: string | null = null
  let lintCmd: string | null = null

  const pkgPath = path.join(cwd, 'package.json')
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'))
      const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) }
      language =
        'typescript' in deps || fs.existsSync(path.join(cwd, 'tsconfig.json'))
          ? 'TypeScript'
          : 'JavaScript'
      if ('next' in deps) framework = 'Next.js'
      else if ('react' in deps) framework = 'React'
      else if ('vue' in deps) framework = 'Vue'
      else if ('svelte' in deps) framework = 'Svelte'
      else if ('express' in deps) framework = 'Express'
      else if ('fastify' in deps) framework = 'Fastify'
      else if ('hono' in deps) framework = 'Hono'
      const scripts = pkg.scripts ?? {}
      buildCmd = scripts.build ? 'npm run build' : null
      testCmd = scripts.test
        ? 'npm test'
        : scripts['test:run']
          ? 'npm run test:run'
          : null
      if (testCmd) {
        if (deps.vitest) targetedTestCmd = 'npx vitest run <test-file>'
        else if (deps.jest) targetedTestCmd = 'npx jest <test-file>'
        else targetedTestCmd = 'npm test -- <test-file>'
      }
      lintCmd = scripts.lint ? 'npm run lint' : scripts.format ? 'npm run format' : null
    } catch {
      // malformed package.json — skip
    }
  } else if (
    fs.existsSync(path.join(cwd, 'pyproject.toml')) ||
    fs.existsSync(path.join(cwd, 'setup.py'))
  ) {
    language = 'Python'
    const tomlPath = path.join(cwd, 'pyproject.toml')
    if (fs.existsSync(tomlPath)) {
      const content = fs.readFileSync(tomlPath, 'utf-8').toLowerCase()
      if (content.includes('django')) framework = 'Django'
      else if (content.includes('fastapi')) framework = 'FastAPI'
      else if (content.includes('flask')) framework = 'Flask'
      else if (content.includes('airflow')) framework = 'Apache Airflow'
    }
    testCmd = 'pytest'
    targetedTestCmd = 'pytest <test-file>'
    lintCmd = 'ruff check .'
  } else if (fs.existsSync(path.join(cwd, 'go.mod'))) {
    language = 'Go'
    buildCmd = 'go build ./...'
    testCmd = 'go test ./...'
    targetedTestCmd = 'go test ./<package>/...'
    lintCmd = 'golangci-lint run'
  } else if (fs.existsSync(path.join(cwd, 'Cargo.toml'))) {
    language = 'Rust'
    buildCmd = 'cargo build'
    testCmd = 'cargo test'
    targetedTestCmd = 'cargo test <test-name>'
    lintCmd = 'cargo clippy'
  } else if (fs.existsSync(path.join(cwd, 'pom.xml'))) {
    language = 'Java'
    framework = 'Maven'
    buildCmd = 'mvn compile'
    testCmd = 'mvn test'
    targetedTestCmd = 'mvn test -Dtest=<TestClass>'
    lintCmd = null
  } else if (
    fs.existsSync(path.join(cwd, 'build.gradle')) ||
    fs.existsSync(path.join(cwd, 'build.gradle.kts'))
  ) {
    language = 'Java/Kotlin'
    framework = 'Gradle'
    buildCmd = './gradlew build'
    testCmd = './gradlew test'
    targetedTestCmd = './gradlew test --tests <TestClass>'
    lintCmd = null
  }

  return { language, framework, buildCmd, testCmd, targetedTestCmd, lintCmd }
}

const IGNORED = new Set(['node_modules', '__pycache__', 'target', 'dist', 'build', '.git', '.legioni'])

function getTopLevelStructure(cwd: string): string {
  const entries = fs
    .readdirSync(cwd)
    .filter(e => !e.startsWith('.') && !IGNORED.has(e))
    .sort()
    .flatMap(e => {
      try {
        const isDir = fs.statSync(path.join(cwd, e)).isDirectory()
        return [isDir ? `${e}/` : e]
      } catch {
        return []
      }
    })

  let result = entries.join('\n')

  for (const candidate of ['src', 'lib', 'app', 'pkg', 'packages']) {
    const dir = path.join(cwd, candidate)
    try {
      if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) continue
    } catch {
      continue
    }
    const sub = fs
      .readdirSync(dir)
      .filter(e => !e.startsWith('.') && !IGNORED.has(e))
      .sort()
      .slice(0, 20)
      .flatMap(e => {
        try {
          const isDir = fs.statSync(path.join(dir, e)).isDirectory()
          return [`  ${e}${isDir ? '/' : ''}`]
        } catch {
          return []
        }
      })
    if (sub.length) result += `\n\n${candidate}/:\n${sub.join('\n')}`
    break
  }

  return result
}

function findExistingInstructionsFile(cwd: string): string | null {
  for (const filename of ['AGENTS.md', 'CLAUDE.md', '.cursorrules']) {
    if (fs.existsSync(path.join(cwd, filename))) return filename
  }
  return null
}

function buildSecuritySection(cwd: string, language: string): string | null {
  const findings: string[] = []

  // Security-related files
  const securityFiles = [
    { name: '.env', risk: 'high' },
    { name: '.env.example', risk: 'info' },
    { name: '.env.local', risk: 'high' },
    { name: 'security.md', risk: 'info' },
    { name: 'SECURITY.md', risk: 'info' },
    { name: '.gitguardian.yml', risk: 'info' },
    { name: '.snyk', risk: 'info' },
    { name: '.npmrc', risk: 'info' },
  ]

  // Check if .env is gitignored
  const envPath = path.join(cwd, '.env')
  const gitignorePath = path.join(cwd, '.gitignore')
  let envGitignored = false
  if (fs.existsSync(gitignorePath) && fs.existsSync(envPath)) {
    const gitignore = fs.readFileSync(gitignorePath, 'utf-8')
    envGitignored = gitignore.includes('.env')
    if (!envGitignored) {
      findings.push(`### ⚠️ .env not in .gitignore\n\n\`.env\` exists but is not listed in \`.gitignore\`. Secrets may be committed.`)
    }
  } else if (fs.existsSync(envPath)) {
    findings.push(`### ⚠️ No .gitignore found\n\n\`.env\` exists but no \`.gitignore\` was found. Secrets may be committed.`)
  }

  const foundFiles = securityFiles
    .filter(f => fs.existsSync(path.join(cwd, f.name)))
    .map(f => {
      if (f.name === '.env' && envGitignored) return `\`${f.name}\``
      if (f.risk === 'high') return `\`${f.name}\` (⚠️ high — ensure it is gitignored)`
      return `\`${f.name}\``
    })

  if (foundFiles.length) {
    findings.push(`### Security files\n\n${foundFiles.join('\n')}`)
  }

  // Detect auth patterns in dependencies
  const authDeps = detectAuthDependencies(cwd, language)
  if (authDeps.length) {
    findings.push(`### Auth-related dependencies\n\n${authDeps.join('\n')}`)
  }

  // Detect dependency audit availability
  const auditCmd = detectAuditCommand(cwd, language)
  if (auditCmd) {
    findings.push(`### Dependency audit\n\nCommand available: \`${auditCmd}\`\n\nRun this periodically to check for known vulnerabilities.`)
  }

  if (!findings.length) return null
  return `## Security Awareness\n\n${findings.join('\n\n')}`
}

function detectAuthDependencies(cwd: string, language: string): string[] {
  const deps: string[] = []

  if (language === 'TypeScript' || language === 'JavaScript') {
    const pkgPath = path.join(cwd, 'package.json')
    if (fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'))
        const allDeps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) }
        const authPatterns = ['passport', 'jsonwebtoken', 'jose', 'bcrypt', 'argon2', 'next-auth', 'lucia', 'better-auth', 'clerk', 'auth0', 'supabase']
        for (const pattern of authPatterns) {
          if (pattern in allDeps) deps.push(`- \`${pattern}\` — authentication/authorization`)
        }
      } catch {
        // malformed package.json
      }
    }
  } else if (language === 'Python') {
    const reqPath = path.join(cwd, 'requirements.txt')
    if (fs.existsSync(reqPath)) {
      const content = fs.readFileSync(reqPath, 'utf-8').toLowerCase()
      const authPatterns = ['django-allauth', 'flask-login', 'fastapi-users', 'python-jose', 'passlib', 'argon2-cffi', 'pyjwt']
      for (const pattern of authPatterns) {
        if (content.includes(pattern)) deps.push(`- \`${pattern}\` — authentication/authorization`)
      }
    }
  }

  return deps
}

function detectAuditCommand(cwd: string, language: string): string | null {
  if (language === 'TypeScript' || language === 'JavaScript') {
    if (fs.existsSync(path.join(cwd, 'package-lock.json'))) return 'npm audit'
    if (fs.existsSync(path.join(cwd, 'yarn.lock'))) return 'yarn audit'
    if (fs.existsSync(path.join(cwd, 'pnpm-lock.yaml'))) return 'pnpm audit'
  } else if (language === 'Python') {
    if (fs.existsSync(path.join(cwd, 'requirements.txt'))) return 'pip-audit'
    if (fs.existsSync(path.join(cwd, 'poetry.lock'))) return 'poetry audit'
  } else if (language === 'Go') {
    if (fs.existsSync(path.join(cwd, 'go.sum'))) return 'govulncheck ./...'
  } else if (language === 'Rust') {
    if (fs.existsSync(path.join(cwd, 'Cargo.lock'))) return 'cargo audit'
  }
  return null
}
